package wstest;
import arc.files.*;import arc.util.*;import mindustry.*;import mindustry.gen.*;import mindustry.io.*;import wstorm.world.*;
/** Real v1.5.0 saved worlds, generated by the already delivered historical JAR, read by v1.7.0. */
public class LegacyChecks{
    public static void run(){
        Fi root=new Fi(System.getProperty("ws.tools")).parent().parent().child("tools/fixtures/v1.5.0");
        for(String name:new String[]{"storm-check.msav","v15-passive.msav","inflight-building.msav"}){
            Vars.logic.reset();SaveIO.load(root.child(name));HeadlessChecks.playing();
            int genome=name.startsWith("inflight")?776655:name.startsWith("v15")?551155:89123;
            StormUnit s=(StormUnit)Groups.unit.find(u->u instanceof StormUnit q&&q.genome==genome);
            HeadlessChecks.check("real-v15-world-upgrades-"+name,s!=null&&Float.isFinite(s.matter)&&s.playerControllable()&&s.buildingCapacity()>=5&&s.controller() instanceof StormAI);
            if(name.startsWith("inflight")){
                HeadlessChecks.check("legacy-single-flight-migrates-without-phantom-extra-blocks",s.buildingsInFlight()==1&&s.debrisTicks==95);
                int before=s.eatenBuildings;s.scanTimer=s.skullTimer=10000;s.buildingTarget=-1;java.util.Arrays.fill(s.targetId,-1);java.util.Arrays.fill(s.targetKind,(byte)0);java.util.Arrays.fill(s.directId,-1);
                for(int i=0;i<95;i++){Time.delta=1;StormLogic.update(s);}
                HeadlessChecks.check("legacy-inflight-building-completes-once",s.eatenBuildings==before+1&&s.buildingsInFlight()==0);
            }
            if(name.startsWith("v15")){boolean held=false;for(int id:s.directId)held|=Groups.unit.getByID(id)!=null;HeadlessChecks.check("legacy-passive-victim-retains-live-entity-link",held);}
        }
        Vars.logic.reset();SaveIO.load(root.parent().child("v1.6.0/pending-flights.msav"));HeadlessChecks.playing();
        StormUnit old=(StormUnit)Groups.unit.find(u->u instanceof StormUnit q&&q.genome==616717);
        HeadlessChecks.check("real-v16-world-migrates-five-flight-slots-and-counters",old!=null&&old.buildingsInFlight()==5&&old.eatenUnits==19&&old.eatenBuildings==23&&old.tentacleHits==4);
        HeadlessChecks.check("v16-post-hit-event-does-not-become-phantom-v17-windup",old.bodyFacing()==120&&old.aimYaw[0]==0&&old.tentacleStrike[0]==-10000&&old.strikeDone[0]);
    }
}
